language: python

python:
  - 3.6

services:
  - docker

env:
  - DOCKER_PYTHON_VERSION=3.4
  - DOCKER_PYTHON_VERSION=3.5
  - DOCKER_PYTHON_VERSION=3.6
  - DOCKER_PYTHON_VERSION=3.7

install:
  - docker build --build-arg PYTHON_VERSION="${DOCKER_PYTHON_VERSION}" -t "putput-py${DOCKER_PYTHON_VERSION}" .

script:
  - docker run "putput-py${DOCKER_PYTHON_VERSION}"
